# Basic data types

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# Three types of data types are list, Dictionary, Tuple

mylist = [20,30,40,50,60,70]
mylist
mylist[0:3]

[20, 30, 40, 50, 60, 70]

[20, 30, 40]

In [4]:
dict = {'chris':'nwaeme', 'raghu':'trainer', 'you': 'participants', 3:'my number'}
dict['chris']
dict.keys()
dict.values()

'nwaeme'

dict_keys(['chris', 'raghu', 'you', 3])

dict_values(['nwaeme', 'trainer', 'participants', 'my number'])

In [5]:
students = {'s_1':['IBM'], 's_2':['infy','wipro','google']}
students['s_1']
students['s_2']
students['s_2'][0]

['IBM']

['infy', 'wipro', 'google']

'infy'

## This is to test Python

In [6]:
# Tuple
tup_ex = (1,2,3,1)
mylist1 =[1,2,3,4,5]
mylist1.append(7)
mylist1


[1, 2, 3, 4, 5, 7]

In [7]:
# !pip install pandas
# !conda install pandas

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('My Uber Drives 2016.csv')
df.head(5)

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
dtype: object

In [13]:
df.tail()

START_DATE*         END_DATE* CATEGORY*            START*  \
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
1151  Unknown Location      3.9  Temporary Site  
1152  Unknown Location     16.2         Meeting  
1153           Gampaha      6.4  Temporary Site  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN

In [14]:
df.isnull()

START_DATE*  END_DATE*  CATEGORY*  START*  STOP*  MILES*  PURPOSE*
0           False      False      False   False  False   False     False
1           False      False      False   False  False   False      True
2           False      False      False   False  False   False     False
3           False      False      False   False  False   False     False
4           False      False      False   False  False   False     False
...           ...        ...        ...     ...    ...     ...       ...
1151        False      False      False   False  False   False     False
1152        False      False      False   False  False   False     False
1153        False      False      False   False  False   False     False
1154        False      False      False   False  False   False     False
1155        False       True       True    True   True   False      True

[1156 rows x 7 columns]

# Changing data types

In [15]:
temp = pd.DataFrame({"A":['1','2','3'], "B":[11,12,13], "C":['12-06-2012','13-06-2015','15-06-2017']})

In [16]:
temp

A   B           C
0  1  11  12-06-2012
1  2  12  13-06-2015
2  3  13  15-06-2017

In [17]:
pd.to_datetime(['2016-jun-02','2002-07-15'])

DatetimeIndex(['2016-06-02', '2002-07-15'], dtype='datetime64[ns]', freq=None)

In [18]:
temp.dtypes

A    object
B     int64
C    object
dtype: object

# Dataset Summarization Methods

In [19]:
df.describe(include='all')

START_DATE*        END_DATE* CATEGORY* START* STOP*        MILES*  \
count              1156             1155      1155   1155  1155   1156.000000   
unique             1155             1154         2    177   188           NaN   
top     6/28/2016 23:34  6/28/2016 23:59  Business   Cary  Cary           NaN   
freq                  2                2      1078    201   203           NaN   
mean                NaN              NaN       NaN    NaN   NaN     21.115398   
std                 NaN              NaN       NaN    NaN   NaN    359.299007   
min                 NaN              NaN       NaN    NaN   NaN      0.500000   
25%                 NaN              NaN       NaN    NaN   NaN      2.900000   
50%                 NaN              NaN       NaN    NaN   NaN      6.000000   
75%                 NaN              NaN       NaN    NaN   NaN     10.400000   
max                 NaN              NaN       NaN    NaN   NaN  12204.700000   

       PURPOSE*  
count       653  
unique       10  
top     Meeting  
freq        187  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   START_DATE*  1156 non-null   object 
 1   END_DATE*    1155 non-null   object 
 2   CATEGORY*    1155 non-null   object 
 3   START*       1155 non-null   object 
 4   STOP*        1155 non-null   object 
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object 
dtypes: float64(1), object(6)
memory usage: 63.3+ KB


In [21]:
# count of unique start locations
df["START*"].value_counts().head()

Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Name: START*, dtype: int64

# Common data manipulation tasks

5 verbs of data manipulation

1. Selecting/indexing
2. Filtering
3. Sorting
4. Mutating/Conditionally adding columns
5. Groupby/Summarize

## Selecting/indexing

In [22]:
df.head()

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  
0     5.1   Meal/Entertain  
1     5.0              NaN  
2     4.8  Errand/Supplies  
3     4.7          Meeting  
4    63.7   Customer Visit

In [23]:
# Positional Indexing
# df.iloc[row,column]
raghu = df.iloc[:, :-1]
raghu

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*  
0          Fort Pierce      5.1  
1          Fort Pierce      5.0  
2          Fort Pierce      4.8  
3          Fort Pierce      4.7  
4      West Palm Beach     63.7  
...                ...      ...  
1151  Unknown Location      3.9  
1152  Unknown Location     16.2  
1153           Gampaha      6.4  
1154         Ilukwatta     48.2  
1155               NaN  12204.7  

[1156 rows x 6 columns]

In [24]:
print(df.shape)
raghu.shape

(1156, 7)


(1156, 6)

In [25]:
# Label based indexing
# df.loc[row,column]
df.loc[:,['START*','STOP*']]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [26]:
df[['START*','STOP*','MILES*']]

START*             STOP*   MILES*
0          Fort Pierce       Fort Pierce      5.1
1          Fort Pierce       Fort Pierce      5.0
2          Fort Pierce       Fort Pierce      4.8
3          Fort Pierce       Fort Pierce      4.7
4          Fort Pierce   West Palm Beach     63.7
...                ...               ...      ...
1151           Kar?chi  Unknown Location      3.9
1152  Unknown Location  Unknown Location     16.2
1153        Katunayake           Gampaha      6.4
1154           Gampaha         Ilukwatta     48.2
1155               NaN               NaN  12204.7

[1156 rows x 3 columns]

In [27]:
abc=df.loc[:,['START*']]
abc 

START*
0          Fort Pierce
1          Fort Pierce
2          Fort Pierce
3          Fort Pierce
4          Fort Pierce
...                ...
1151           Kar?chi
1152  Unknown Location
1153        Katunayake
1154           Gampaha
1155               NaN

[1156 rows x 1 columns]

**Extract first 5 rows and columns of START_DATE* and MILES***

In [28]:
df.loc[:4,['START_DATE*','MILES*']]

START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7

In [29]:
df.iloc[:5,[0,5]]

START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7

# Filtering

In [30]:
df2 = df[df['MILES*'] > 10]
df2

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
22     1/12/2016 16:02   1/12/2016 17:00  Business          New York   
23     1/13/2016 13:54   1/13/2016 14:07  Business          Downtown   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
22       Queens County     15.1         Meeting  
23             Gulfton     11.2         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[316 rows x 7 columns]

In [31]:
df3 = df.loc[df['MILES*'] > 10, ['START_DATE*','MILES*']]
df3

START_DATE*   MILES*
4       1/6/2016 14:42     63.7
9      1/10/2016 12:17     16.5
10     1/10/2016 15:08     10.8
22     1/12/2016 16:02     15.1
23     1/13/2016 13:54     11.2
...                ...      ...
1134  12/29/2016 11:28     11.9
1144  12/29/2016 23:14     12.9
1152  12/31/2016 15:03     16.2
1154  12/31/2016 22:08     48.2
1155            Totals  12204.7

[316 rows x 2 columns]

In [32]:
#Find out all rides from New York
df.loc[df['START*']=='New York',['MILES*']].head()

MILES*
10     10.8
22     15.1
106    13.0
423    16.3

In [33]:
df.loc[df['MILES*'] >10,['MILES*']]

#df3 = df.loc[df['MILES*'] > 10, ['START_DATE*','MILES*']]
#df3

MILES*
4        63.7
9        16.5
10       10.8
22       15.1
23       11.2
...       ...
1134     11.9
1144     12.9
1152     16.2
1154     48.2
1155  12204.7

[316 rows x 1 columns]

In [34]:
#Find out all rides to carry & Morrisville
my_rides = df[df['START*'].isin(['Cary','Morrisville'])]
my_rides.head(10)

START_DATE*        END_DATE* CATEGORY*       START*        STOP*  \
7    1/7/2016 13:27   1/7/2016 13:33  Business         Cary         Cary   
8    1/10/2016 8:05   1/10/2016 8:25  Business         Cary  Morrisville   
27   1/15/2016 0:41   1/15/2016 1:01  Business  Morrisville         Cary   
28  1/15/2016 11:43  1/15/2016 12:03  Business         Cary       Durham   
30  1/18/2016 14:55  1/18/2016 15:06  Business         Cary         Cary   
34  1/20/2016 10:36  1/20/2016 11:11  Business         Cary      Raleigh   
37  1/21/2016 14:25  1/21/2016 14:29  Business         Cary         Cary   
38  1/21/2016 14:43  1/21/2016 14:51  Business         Cary         Cary   
39  1/21/2016 16:01  1/21/2016 16:06  Business         Cary         Cary   
43  1/26/2016 17:17  1/26/2016 17:22  Business         Cary         Cary   

    MILES*         PURPOSE*  
7      0.8          Meeting  
8      8.3          Meeting  
27     8.0  Errand/Supplies  
28    10.4   Meal/Entertain  
30     4.8   Meal/Entertain  
34    17.1          Meeting  
37     1.6  Errand/Supplies  
38     2.4   Meal/Entertain  
39     1.0   Meal/Entertain  
43     1.4  Errand/Supplies

In [35]:
#Find out all rides to carry & Morrisville
my_rides = df[df['START*'].isin(['Cary','Morrisville'])]
my_rides.iloc[0:5,:]

START_DATE*        END_DATE* CATEGORY*       START*        STOP*  \
7    1/7/2016 13:27   1/7/2016 13:33  Business         Cary         Cary   
8    1/10/2016 8:05   1/10/2016 8:25  Business         Cary  Morrisville   
27   1/15/2016 0:41   1/15/2016 1:01  Business  Morrisville         Cary   
28  1/15/2016 11:43  1/15/2016 12:03  Business         Cary       Durham   
30  1/18/2016 14:55  1/18/2016 15:06  Business         Cary         Cary   

    MILES*         PURPOSE*  
7      0.8          Meeting  
8      8.3          Meeting  
27     8.0  Errand/Supplies  
28    10.4   Meal/Entertain  
30     4.8   Meal/Entertain

In [36]:
df3 = df.loc[(df['MILES*']>10) & (df['START*'].isin(['Carry','New York']))]
df4 = df3.reset_index(drop=True)
df4

START_DATE*        END_DATE* CATEGORY*    START*             STOP*  \
0  1/10/2016 15:08  1/10/2016 15:51  Business  New York            Queens   
1  1/12/2016 16:02  1/12/2016 17:00  Business  New York     Queens County   
2  2/14/2016 16:35  2/14/2016 17:02  Business  New York  Long Island City   
3  6/10/2016 15:19  6/10/2016 16:28  Business  New York           Jamaica   

   MILES* PURPOSE*  
0    10.8  Meeting  
1    15.1  Meeting  
2    13.0  Meeting  
3    16.3  Meeting

# Sorting

In [37]:
 df.sort_values(by=['MILES*'], ascending=False).head(5)

START_DATE*         END_DATE* CATEGORY*            START*  \
1155            Totals               NaN       NaN               NaN   
269    3/25/2016 16:52   3/25/2016 22:22  Business             Latta   
270    3/25/2016 22:54    3/26/2016 1:39  Business      Jacksonville   
881   10/30/2016 15:22  10/30/2016 18:23  Business         Asheville   
776    9/27/2016 21:01    9/28/2016 2:37  Business  Unknown Location   

                 STOP*   MILES*        PURPOSE*  
1155               NaN  12204.7             NaN  
269       Jacksonville    310.3  Customer Visit  
270          Kissimmee    201.0         Meeting  
881             Mebane    195.9             NaN  
776   Unknown Location    195.6             NaN

In [38]:
 df.sort_values(by=['START*','MILES*'], ascending=(True,False)).head(5)

START_DATE*         END_DATE* CATEGORY*  START*        STOP*  \
906   11/4/2016 21:04   11/4/2016 21:20  Business   Agnew         Cory   
911   11/6/2016 10:50   11/6/2016 11:04  Business   Agnew  Renaissance   
908    11/5/2016 8:34    11/5/2016 8:43  Business   Agnew  Renaissance   
910   11/5/2016 19:20   11/5/2016 19:28  Business   Agnew        Agnew   
879  10/30/2016 12:58  10/30/2016 13:18  Business  Almond  Bryson City   

     MILES* PURPOSE*  
906     4.3      NaN  
911     2.4      NaN  
908     2.2      NaN  
910     2.2      NaN  
879    15.2      NaN

# Conditionally Adding Column

In [39]:
import numpy as np
df['miles_cat*'] = np.where(df['MILES*']>5, 'long trip', 'short trip')
df.head(5)

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  miles_cat*  
0     5.1   Meal/Entertain   long trip  
1     5.0              NaN  short trip  
2     4.8  Errand/Supplies  short trip  
3     4.7          Meeting  short trip  
4    63.7   Customer Visit   long trip

In [40]:
df['my_year*']=np.array(2000)
df.head(5)

START_DATE*       END_DATE* CATEGORY*       START*            STOP*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce      Fort Pierce   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce      Fort Pierce   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce      Fort Pierce   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce      Fort Pierce   
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce  West Palm Beach   

   MILES*         PURPOSE*  miles_cat*  my_year*  
0     5.1   Meal/Entertain   long trip      2000  
1     5.0              NaN  short trip      2000  
2     4.8  Errand/Supplies  short trip      2000  
3     4.7          Meeting  short trip      2000  
4    63.7   Customer Visit   long trip      2000

# Grouping (Split, Apply, Combine)

In [41]:
# Groupby Summarize. Note agg(is an aggregate function)
#df.groupby('START*')['MILES*'].agg('mean')
df.groupby('START*')['MILES*'].mean()

START*
Agnew                2.775000
Almond              15.200000
Apex                 5.341176
Arabi               17.000000
Arlington            4.900000
                      ...    
West University      2.200000
Weston               4.000000
Westpark Place       2.182353
Whitebridge          4.020588
Winston Salem      133.600000
Name: MILES*, Length: 177, dtype: float64

In [42]:
df.groupby('START*').mean()

MILES*  my_year*
START*                               
Agnew              2.775000    2000.0
Almond            15.200000    2000.0
Apex               5.341176    2000.0
Arabi             17.000000    2000.0
Arlington          4.900000    2000.0
...                     ...       ...
West University    2.200000    2000.0
Weston             4.000000    2000.0
Westpark Place     2.182353    2000.0
Whitebridge        4.020588    2000.0
Winston Salem    133.600000    2000.0

[177 rows x 2 columns]

In [43]:
df.groupby(['START*','STOP*']).agg(['mean','sum']).head(20)

MILES*         \
                                                           mean    sum   
START*                    STOP*                                          
Agnew                     Agnew                        2.200000    2.2   
                          Cory                         4.300000    4.3   
                          Renaissance                  2.300000    4.6   
Almond                    Bryson City                 15.200000   15.2   
Apex                      Apex                         2.150000    4.3   
                          Cary                         5.792308   75.3   
                          Eagle Rock                   2.200000    2.2   
                          Holly Springs                9.000000    9.0   
Arabi                     Metairie                    17.000000   17.0   
Arlington                 Washington                   4.900000    4.9   
Arlington Park at Amberly Lexington Park at Amberly    1.300000    1.3   
Asheville                 Mebane                     195.900000  195.9   
                          Topton                      91.800000   91.8   
Austin                    Katy                       136.000000  136.0   
Banner Elk                Banner Elk                   6.680000   33.4   
                          Boone                       15.100000   15.1   
                          Elk Park                    22.400000   22.4   
                          Newland                     28.100000   28.1   
Bellevue                  Seattle                     12.900000   12.9   
Berkeley                  El Cerrito                   2.300000    2.3   

                                                    my_year*         
                                                        mean    sum  
START*                    STOP*                                      
Agnew                     Agnew                       2000.0   2000  
                          Cory                        2000.0   2000  
                          Renaissance                 2000.0   4000  
Almond                    Bryson City                 2000.0   2000  
Apex                      Apex                        2000.0   4000  
                          Cary                        2000.0  26000  
                          Eagle Rock                  2000.0   2000  
                          Holly Springs               2000.0   2000  
Arabi                     Metairie                    2000.0   2000  
Arlington                 Washington                  2000.0   2000  
Arlington Park at Amberly Lexington Park at Amberly   2000.0   2000  
Asheville                 Mebane                      2000.0   2000  
                          Topton                      2000.0   2000  
Austin                    Katy                        2000.0   2000  
Banner Elk                Banner Elk                  2000.0  10000  
                          Boone                       2000.0   2000  
                          Elk Park                    2000.0   2000  
                          Newland                     2000.0   2000  
Bellevue                  Seattle                     2000.0   2000  
Berkeley                  El Cerrito                  2000.0   2000

In [44]:
# for each start loc find the mean distance travelled
df.groupby('START*')['MILES*'].agg('mean').head()

START*
Agnew         2.775000
Almond       15.200000
Apex          5.341176
Arabi        17.000000
Arlington     4.900000
Name: MILES*, dtype: float64

In [45]:
# for each start loc find the mean & the total dist travelled
df.groupby('START*').agg(['mean','sum']).head()

MILES*       my_year*       
                mean   sum     mean    sum
START*                                    
Agnew       2.775000  11.1   2000.0   8000
Almond     15.200000  15.2   2000.0   2000
Apex        5.341176  90.8   2000.0  34000
Arabi      17.000000  17.0   2000.0   2000
Arlington   4.900000   4.9   2000.0   2000

In [46]:
# # for each start loc find the mean & the total dist travelled
# df.groupby('START*').agg(['DATE*','MILES*']).head()
# df.groupby('START*')['MILES*'].agg('mean').head()
df.tail(5)


START_DATE*         END_DATE* CATEGORY*            START*  \
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  miles_cat*  my_year*  
1151  Unknown Location      3.9  Temporary Site  short trip      2000  
1152  Unknown Location     16.2         Meeting   long trip      2000  
1153           Gampaha      6.4  Temporary Site   long trip      2000  
1154         Ilukwatta     48.2  Temporary Site   long trip      2000  
1155               NaN  12204.7             NaN   long trip      2000

**Find most recent & the earliest traveled date and mean distance traveled for each start city**

In [47]:
df = df.iloc[:-1,:]
df.tail()
df['START_DATE*'] = pd.to_datetime(df['START_DATE*'])
df.dtypes 

START_DATE*         END_DATE* CATEGORY*            START*  \
1150   12/31/2016 1:07   12/31/2016 1:14  Business           Kar?chi   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   

                 STOP*  MILES*        PURPOSE*  miles_cat*  my_year*  
1150           Kar?chi     0.7         Meeting  short trip      2000  
1151  Unknown Location     3.9  Temporary Site  short trip      2000  
1152  Unknown Location    16.2         Meeting   long trip      2000  
1153           Gampaha     6.4  Temporary Site   long trip      2000  
1154         Ilukwatta    48.2  Temporary Site   long trip      2000

START_DATE*    datetime64[ns]
END_DATE*              object
CATEGORY*              object
START*                 object
STOP*                  object
MILES*                float64
PURPOSE*               object
miles_cat*             object
my_year*                int32
dtype: object

In [48]:
# Solution
res = df.groupby('START*').agg({'MILES*':'mean',
                                'START_DATE*':['min','max']})
res
res.reset_index(inplace=True)

res
res.columns=['START_CITY','AVG_DIST','EARIEST_TRIP', 'RECENT_TRIP']
res.to_csv("raghu.csv")

MILES*         START_DATE*                    
                       mean                 min                 max
START*                                                             
Agnew              2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
Almond            15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
Apex               5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
Arabi             17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
Arlington          4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
...                     ...                 ...                 ...
West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
Weston             4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
Westpark Place     2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
Whitebridge        4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
Winston Salem    133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 3 columns]

START*      MILES*         START_DATE*                    
                            mean                 min                 max
0              Agnew    2.775000 2016-11-04 21:04:00 2016-11-06 10:50:00
1             Almond   15.200000 2016-10-30 12:58:00 2016-10-30 12:58:00
2               Apex    5.341176 2016-01-29 21:21:00 2016-12-12 14:26:00
3              Arabi   17.000000 2016-06-25 10:50:00 2016-06-25 10:50:00
4          Arlington    4.900000 2016-08-02 11:51:00 2016-08-02 11:51:00
..               ...         ...                 ...                 ...
172  West University    2.200000 2016-03-10 14:39:00 2016-03-16 18:43:00
173           Weston    4.000000 2016-03-05 12:57:00 2016-06-05 15:57:00
174   Westpark Place    2.182353 2016-02-26 11:05:00 2016-11-03 14:13:00
175      Whitebridge    4.020588 2016-01-19 09:09:00 2016-11-03 13:42:00
176    Winston Salem  133.600000 2016-10-28 18:13:00 2016-10-28 18:13:00

[177 rows x 4 columns]

# Loops and Function

In [49]:
# Basic for loop
res = []
temp = [1,2,3,4]
for i in temp:
    res.append(i*i)
res

[1, 4, 9, 16]

In [50]:
# List comprehension way
[x*x for x in temp]

[1, 4, 9, 16]

# NumPy

In [51]:
import numpy as np

In [52]:
distance = [45 ,50, 35]
spd = [5,10,7]
dist = np.array(distance)
speed = np.array(spd)
time = dist/spd
print(time)

[9. 5. 5.]


In [53]:
a = np.array((1,2,3,4,5))
b = np.array((6,7,8,9,10))
print(a + b)

[ 7  9 11 13 15]


In [54]:
ed = np.arange(15)
ed
adn = np.arange(5,56,5)
adn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [55]:
ome = np.linspace(10,100,10)
ome   

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [56]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.ones((3,2))+7

array([[8., 8.],
       [8., 8.],
       [8., 8.]])

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.diag(array([1,3,5,3,4,5]))

NameError: name 'array' is not defined

# Visualization Library
**matplotlib**

**seaborn**

In [73]:
import seaborn as sns
from scipy.stats import spearmanr
import matplotlib.pyplot as plt

In [71]:
df = pd.read_csv('USA_Housing.csv')
df.head(5)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [72]:
df.shape

(5000, 7)