Numpy - Numerical Python

Advantages of Numpy Arrays:

    1. Allows several Mathematical Operations
    2. Faster operations

In [1]:
import numpy as np # Numpy is a library in python
from time import process_time

In [2]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 

end_time = process_time()

print(end_time - start_time)

0.0


In [3]:
# List
List1 = [1,2,3,4,5]
print(List1)
type(List1)

[1, 2, 3, 4, 5]


list

In [4]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [5]:
# Creating a One dimensional array
a = np.array([1,2,2,3])
print(a)

[1 2 2 3]


In [6]:
a.shape

(4,)

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b.shape

(2, 4)

In [9]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial Placeholders in numpy arrays

In [10]:
# Create a numpy array of Zeros
x = np.zeros([4,5])
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# Create a numpy array of ones
y = np.ones([3,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# array of a particular values

z = np.full((5,4), 4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [13]:
# Create an identity matrix
s = np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# Create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.5404473  0.41704179 0.56179445 0.5662093 ]
 [0.13448498 0.64768386 0.11015123 0.7123508 ]
 [0.18017786 0.84669844 0.26138689 0.9675568 ]]


In [15]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[30 34 55 85 68]
 [88 36 87 31 11]
 [21 89 10 34 26]]


In [16]:
# array of evenly spaced values ---> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [17]:
# array of evenly spaced values ---> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [18]:
# Convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [19]:
c = np.random.randint(10,90,(5,5))
print(c)

[[15 16 52 37 49]
 [62 54 71 51 78]
 [20 28 53 62 72]
 [52 63 85 20 22]
 [72 60 45 57 57]]


In [20]:
# array dimension
print(c.shape)

(5, 5)


In [21]:
# number of dimension
print(c.ndim)

2


In [22]:
# number of elements in an array
print(c.size)

25


In [23]:
#checking the data type of values in the array
print(c.dtype)

int32


Mathematical operation on a np-array

In [24]:
list3 = [1,2,3,4,5]
list4 = [6,7,8,9,10]

print(list3 + list4) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [25]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [26]:
print(a)
print(b)

[[8 6 5]
 [2 8 4]
 [3 3 3]]
[[17 10 13]
 [15 18 14]
 [17 18 11]]


In [27]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 16 18]
 [17 26 18]
 [20 21 14]]
[[ -9  -4  -8]
 [-13 -10 -10]
 [-14 -15  -8]]
[[136  60  65]
 [ 30 144  56]
 [ 51  54  33]]
[[0.47058824 0.6        0.38461538]
 [0.13333333 0.44444444 0.28571429]
 [0.17647059 0.16666667 0.27272727]]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [29]:
print(a)
print(b)

[[6 6 6]
 [6 7 4]
 [2 9 1]]
[[15 13 16]
 [17 15 10]
 [13 11 14]]


In [30]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[21 19 22]
 [23 22 14]
 [15 20 15]]
[[ -9  -7 -10]
 [-11  -8  -6]
 [-11  -2 -13]]
[[ 90  78  96]
 [102 105  40]
 [ 26  99  14]]


Array Manipulation

In [31]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 8 2]
 [3 4 0]]
(2, 3)


In [32]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 3]
 [8 4]
 [2 0]]
(3, 2)


In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 4 4]
 [8 9 8]]
(2, 3)


In [34]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 8]
 [4 9]
 [4 8]]
(3, 2)


In [35]:
#reshaping an array 
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 8 4]
 [0 1 1]]
(2, 3)


In [36]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 8]
 [4 0]
 [1 1]]
(3, 2)
